### ISSUE TITLE
解压完之后找不到x4-station-calc.exe在哪

### ISSUE THREAD

**Issue by NA-XI** [darknightghost/x4-station-calc#5]
![awa](https://user-images.githubusercontent.com/78271168/106362543-648d7580-635e-11eb-8794-f84339345540.png)

**Comment by darknightghost** [comment]
你在源代码能找到exe才有鬼.这个你要自己搭建环境照readme编译可执行文件.
编译好的在这[https://github.com/darknightghost/x4-station-calc/wiki](url),
帖子里面我都贴出来了源代码在哪构建好的在哪你跑源代码里找构建好的可执行文件.
另外linux下的版本要自己编译.

**Comment by NA-XI** [comment]
啊这。。。看来是我大意了（手动狗头）

**Comment by darknightghost** [comment]
> 啊这。。。看来是我大意了（手动狗头）

你应该是没怎么用过这类代码托管平台吧,而且应该不怎么写代码,正常来说那玩意是源代码一眼就能看出来,而且从Release里面下载还算正常行为,结果你master分支给下载了...

**Comment by NA-XI** [comment]
老实巴交的玩家一枚，哪懂代码，大学时只简单学了一点C和汇编

**Comment by NA-XI** [comment]
![20210201-1](https://user-images.githubusercontent.com/78271168/106479194-0212b180-64e5-11eb-9803-750d3c5e5c35.png)
我哭着又回来了，大佬，这个该咋办

**Comment by darknightghost** [comment]
> 
> 
> ![20210201-1](https://user-images.githubusercontent.com/78271168/106479194-0212b180-64e5-11eb-9803-750d3c5e5c35.png)
> 我哭着又回来了，大佬，这个该咋办

这是啥

**Comment by NA-XI** [comment]
这是我首次启动选择游戏路径的时候，一直没法找到对应文件

**Comment by darknightghost** [comment]
> 
> 
> 这是我首次启动选择游戏路径的时候，一直没法找到对应文件

那是你游戏路径没找对, 自行百度steam游戏如何浏览本地文件,x4的游戏目录根本没videos那个文件夹.
游戏的路径里面长这样:
![图片](https://user-images.githubusercontent.com/6492167/106543322-73338280-6540-11eb-84f3-56f844787692.png)
![图片](https://user-images.githubusercontent.com/6492167/106543272-5303c380-6540-11eb-8e70-8399b959bde5.png)
里面那一堆cat,dat还有x4.exe是识别的关键.

**Comment by NA-XI** [comment]
尴尬，我多选了一步，已经弄好了，再次感谢大佬耐心解答
