### ISSUE TITLE
OpenSSL Linux Prerequisite

### ISSUE THREAD

**Issue by RPINerd** [darknightghost/x4-station-calc#6]
On ubuntu based systems, it's a common issue to have issues building with cmake even when openssl is installed. You have to install libssl-dev to get around this

**Comment by darknightghost** [comment]
It is beacuse most packages without -dev suffix do not contain the files for developer such as header files in debian-based distributions. For example, package `libssh2` doest not contain header files, the header files are in package `libssh2-1-dev`.
Another reason is debian-based distributions like to split a software into a laot of package. For example `ffmpeg`, `libavcodec`, `libavcodec-dev`, `libswscale`, `libswscale-dev`, `libavfilter`, 'libavfilter-dev'... are all splitted from ffmpeg, there source code is the same package.
I will write a list about how to install the dependencies in README.md.

**Comment by darknightghost** [comment]
`README.md` has been updated in the master branch.
